Repository Mgrdich/LLM_service, pull requests merged in 2024-05, with the labels that each got.

#5 add exception classes, and DAO layer
  backend/src/main/java/com/llm_service/llm_service/controller/conversation/ConversationController.java
  backend/src/main/java/com/llm_service/llm_service/controller/conversation/ConversationControllerMapper.java
  backend/src/main/java/com/llm_service/llm_service/controller/conversation/ConversationResponse.java
  backend/src/main/java/com/llm_service/llm_service/exception/conversation/ConversationAlreadyExistsException.java
  backend/src/main/java/com/llm_service/llm_service/exception/conversation/ConversationNotFoundException.java
  backend/src/main/java/com/llm_service/llm_service/exception/user/UserAlreadyExistsException.java
  backend/src/main/java/com/llm_service/llm_service/exception/user/UserNotFoundException.java
  backend/src/main/java/com/llm_service/llm_service/service/ConversationService.java
Labels: enhancement

#6 Initialize Database Discussion and Conversations.
  backend/src/main/java/com/llm_service/llm_service/persistance/entities/BaseEntity.java
  backend/src/main/java/com/llm_service/llm_service/persistance/entities/ConversationEntity.java
  backend/src/main/java/com/llm_service/llm_service/persistance/entities/DiscussionEntity.java
  backend/src/main/java/com/llm_service/llm_service/persistance/entities/DiscussionRole.java
Labels: enhancement

#10 Swagger
  backend/pom.xml
Labels: documentation

#34 Welcome page styling modifications
  frontend/src/pages/Welcome/Welcome.tsx
  frontend/tailwind.config.js
Labels: enhancement

#56 added username and password validations
  backend/pom.xml
  backend/src/main/java/com/llm_service/llm_service/constraint/PasswordConstraintValidator.java
  backend/src/main/java/com/llm_service/llm_service/constraint/UsernameConstraintValidator.java
  backend/src/main/java/com/llm_service/llm_service/constraint/ValidPassword.java
  backend/src/main/java/com/llm_service/llm_service/constraint/ValidUsername.java
  backend/src/main/java/com/llm_service/llm_service/controller/user/UserController.java
  backend/src/main/java/com/llm_service/llm_service/controller/user/UserRequest.java
  backend/src/main/java/com/llm_service/llm_service/controller/user/ValidationErrorResponse.java
Labels: bug

#57 FE: add frontend validations
  backend/src/main/java/com/llm_service/llm_service/constraint/UsernameConstraintValidator.java
  docker-compose.yml
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/pages/Auth/ForgotPassword.tsx
  frontend/src/pages/Auth/Login.tsx
  frontend/src/pages/Auth/Register.tsx
  frontend/src/pages/Conversation/Navbar/EditConversationModal.tsx
  frontend/src/pages/Conversation/Prompt/Prompt.tsx
  frontend/src/ui/Checkbox.tsx
  frontend/src/ui/ErrorLabel.tsx
  frontend/src/ui/FormSubmitButton.tsx
  frontend/src/ui/Input.tsx
  frontend/src/ui/InputWithLabel.tsx
Labels: bug, enhancement
